server:
  port: 8082

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update

  eureka:
    client:
      fetch-registery: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true