version: '3.7'

services:
  db-inventory-service:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    ports:
      - '5432:5432'
